<?php

declare(strict_types=1);

namespace OpenTelemetry\DistroTests\UnitTests\UtilTests\ConfigTests;

use OpenTelemetry\DistroTests\Util\Config\IntOptionParser;
use OpenTelemetry\DistroTests\Util\Config\NumericOptionParser;
use OpenTelemetry\DistroTests\Util\RandomUtil;
use Override;

/**
 * @extends NumericOptionTestValuesGeneratorBase<int>
 */
class IntOptionTestValuesGenerator extends NumericOptionTestValuesGeneratorBase
{
    public function __construct(
        protected IntOptionParser $optionParser
    ) {
    }

    /**
     * @return IntOptionParser
     */
    protected function optionParser(): NumericOptionParser
    {
        return $this->optionParser;
    }

    /**
     * @return int
     */
    final protected static function maxValueSupportedByType(): int
    {
        return PHP_INT_MAX;
    }

    /**
     * @return int
     */
    final protected static function minValueSupportedByType(): int
    {
        return PHP_INT_MIN;
    }

    /**
     * @return iterable<OptionTestValidValue<int>>
     */
    protected function manualInterestingValues(): iterable
    {
        return self::intManualInterestingValues();
    }

    /**
     * @return iterable<int>
     */
    protected function autoGeneratedInterestingValuesToDiff(): iterable
    {
        return self::intInterestingValuesToDiff();
    }

    /**
     * @return iterable<int>
     */
    protected function autoGeneratedInterestingValueDiffs(): iterable
    {
        return self::intInterestingDiffs();
    }

    /**
     * @param int $min
     * @param int $max
     */
    protected static function randomValue($min, $max): int
    {
        return RandomUtil::generateIntInRange($min, $max);
    }

    /**
     * @param int $value
     *
     * @return OptionTestValidValue<int>
     */
    protected static function createOptionTestValidValue($value): OptionTestValidValue
    {
        return new OptionTestValidValue(strval($value), $value);
    }

    /** @inheritDoc */
    #[Override]
    public function invalidRawValues(): iterable
    {
        yield from ['0.0', '1.0', '-1.0', '1.5', '-1.5', '20.2', '-30.3'];
        yield from parent::invalidRawValues();
    }
}
