; This file contains the various settings for the OpenTelemetry PHP distro. For

[opentelemetry_distro]
;opentelemetry_distro.enabled = true
;opentelemetry_distro.log_level = "INFO"
;opentelemetry_distro.log_level_stderr = "INFO"